//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.CasualWorkers = new HashSet<CasualWorker>();
            this.Deliveries = new HashSet<Delivery>();
            this.Documents = new HashSet<Document>();
            this.Expenses = new HashSet<Expense>();
            this.Factories = new HashSet<Factory>();
            this.Incomes = new HashSet<Income>();
            this.Stocks = new HashSet<Stock>();
            this.Stores = new HashSet<Store>();
            this.WeightNotes = new HashSet<WeightNote>();
            this.Activities = new HashSet<Activity>();
            this.Sectors = new HashSet<Sector>();
            this.Order = new HashSet<Order>();
        }
    
        public long BranchId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<CasualWorker> CasualWorkers { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Factory> Factories { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
        public virtual ICollection<WeightNote> WeightNotes { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
